Repository ucsb-cs156-s24/proj-gauchoride-s24-5pm-5, pull requests merged in 2024-05, with the labels that each got.

#19 Fixed "Apply to be rider" should not be visible to non-user
  frontend/src/main/components/Nav/AppNavbar.js
Labels: Ready for Staff CR

#20 Fixed BUG driver availability creation
  frontend/src/main/pages/Drivers/DriverAvailabilityIndexPage.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityIndexPage.test.js
Labels: 5

#21 Fixed invalid ride form date error text
  frontend/src/main/components/Ride/RideForm.js
Labels: Ready for Staff CR

#22 Added swagger navbar switch in .env
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: Ready for Staff CR

#35 MD feature toggle sorted
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/pages/AdminUsersPage.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 5

#24 Change the driver id into dropdowns in shift form
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
  frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
  frontend/src/tests/pages/Shift/ShiftEditPage.test.js
Labels: 10

#26 Expose commit information at /api/systemInfo #12
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/gauchoride/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/SystemInfoServiceImplTests.java
Labels: 10

#29 Fixes labels/bad input/example input for Improve usability of the DriverAvailabilities Create Page #13
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
Labels: 10

#30 WG - Updated which tabs appear based on user roles
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#39 FEATURE and DOCUMENTATION: Make /api/systemInfo available even when not logged in, AND document dokku step. #38
  README.md
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/SystemInfoController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/SystemInfoControllerTests.java
Labels: 5

#42 pc - add test for SecurityConfig
  src/test/java/edu/ucsb/cs156/gauchoride/config/SecurityConfigTests.java
Labels: staff-PR

#36 Fix BUG: Github repo link is hardcoded #18
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: Ready for Staff CR, s24-5pm-5

#40 Upgrade backend to spring3
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  pom.xml
  src/main/java/edu/ucsb/cs156/gauchoride/aop/LoggingAspect.java
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UserProfileController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/ChatMessage.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/RiderApplication.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Shift.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/gauchoride/config/SecurityConfigTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/CurrentUserServiceTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/services/GrantedAuthoritiesServiceTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/testconfig/TestConfig.java
Labels: s24-5pm-5
